### ISSUE TITLE
env.monitor deprecated

### ISSUE THREAD

**Issue by markusdumke** [paulhendricks/gym-R#5] opened 2017-02-08 09:49 UTC
Hi, 
when I run your example code, the line `env_monitor_start(client, instance_id, outdir, force = TRUE, resume = FALSE)` fails with **Error: API did not return json**. 

And in the command line I get this error **gym.error.Error: env.monitor has been deprecated as of 12/23/2016. Remove your call to `env.monitor.start(directory)` and instead wrap your env with `env = gym.wrappers.Monitor(env, directory)` to record data.**

**Comment by paulhendricks** [comment] 2017-02-11 01:10
Thanks for the heads up! I'll take a look and see what I find.

**Comment by kkweon** [comment] 2017-02-28 23:14
#### This is not a bug of `gym-R`
The problem was that `gym-http-api` was not using the latest `gym` when there was a change in using monitor wrapper.  This fix was merged to `gym-http-api` lately and it's resolved now. (Check [here](https://github.com/openai/gym-http-api/pull/30/commits/fab6d82836e25e8ec7ab0d8de19484f6a56b33a5))

#### Conclusion
Pull the latest `gym-http-pi` and it will work without any issue.

**Comment by paulhendricks** [comment] 2017-03-04 19:44
Using gym-R version 0.1.0 and using @kkweon's recommendation, I'm not finding a bug with gym-R. I'm considering this issue closed.

**Closed as completed by paulhendricks** 2017-03-04 19:44 UTC
Labels: bug
